CREATE DATABASE blog DEFAULT CHARSET  utf8mb4 COLLATE  utf8mb4_general_ci;

USE blog;

CREATE TABLE FASHION_BLOG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255),
  CONTENT VARCHAR(2048),  -- TEXT 대신 CONTENT 사용
  LINK VARCHAR(2048),
  IMAGE VARCHAR(2048)
) DEFAULT CHARSET=utf8mb4;

select * from fashion_blog;

DROP DATABASE blog;
